name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]    
  workflow_dispatch:

jobs:
  validation:
    uses: microsoft/action-python/.github/workflows/validation.yml@0.3.5
    with:
      workdir: partnercenter
