name: Python CI
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  azdev-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: azdev setup
        run: |
          python -m venv env
          source env/bin/activate
          pip install azdev

          azdev setup -r .
          azdev extension repo add .
          azdev extension add partnercenter
      - name: azdev style
        run: |
          source env/bin/activate
          OUTPUT=$(azdev style partnercenter)

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "STYLE_OUTPUT<<$EOF" >> $GITHUB_ENV
          echo $OUTPUT >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
      - name: Post Style result to PR
        uses: mshick/add-pr-comment@v1
        continue-on-error: true
        with:
          message: ${{ env.STYLE_OUTPUT }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default

  azdev-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: azdev setup
        run: |
          python -m venv env
          source env/bin/activate
          pip install azdev

          azdev setup -r .
          azdev extension repo add .
          azdev extension add partnercenter
      - name: azdev linter
        run: |
          source env/bin/activate
          OUTPUT=$(azdev linter partnercenter)

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "LINTER_OUTPUT<<$EOF" >> $GITHUB_ENV
          echo $OUTPUT >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV          
      - name: Post Linter result to PR
        uses: mshick/add-pr-comment@v1
        continue-on-error: true
        with:
          message: ${{ env.LINTER_OUTPUT }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default

  # azdev-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
  #     - run: |
  #         python -m venv env
  #         source env/bin/activate
  #         pip install azdev
  #         azdev setup -r .
  #         azdev extension repo add ../partnercenter-cli-extension/
  #         azdev extension add partnercenter
  #     - name: azdev test
  #       run: |
  #         source env/bin/activate
  #         azdev test partnercenter
